#!/bin/sh

#	autopac: Automate installing and upgrading packages on most systems

#   Copyright 2023, 2024, 2025	Eric Hernandez

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       https://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#	See the License for the specific language governing permissions and
#   limitations under the License.

[ ! "$1" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ] &&
printf "Usage: autopac [OPTION] \nOptions:\n -i  Install software \n -u  Upgrade software \n -f  Upgrade flatpaks \n -h  Show options\n" && exit 0

[ "$1" = "-v" ] && printf "autopac 1.1 \n" && exit 0

[ "$1" = "-f" ] && [ -f /usr/bin/flatpak ] && flatpak update -y && exit 0

[ "$1" = "-s" ] && [ -f /usr/bin/snap ] && sudo snap refresh && exit 0

mkdir $HOME/.config/autopac/ 2> /dev/null
software_list="$HOME/.config/autopac/software.config"

ins() {
	if [ "$2" = "-i" ]; then
		if [ ! -f $software_list ]; then
			touch $software_list 2> /dev/null
			printf "NOTICE: The software list at $software_list does not exist\n"
			printf "Please write the names of the packages you want installed there and try again\n"
			exit 1
		fi

		for pkg in $(cat $software_list); do
			echo "y" | $1 $pkg
		done

		exit 0
	fi
}

export mgr="/usr/bin/apt /usr/bin/dnf /usr/bin/pacman
            /sbin/apk   /usr/sbin/pkg /usr/sbin/pkg_add"
for item in ${mgr}; do
    if [ -f $item ]; then
        pkgMgr=$item
        break
    fi
done

case "$pkgMgr" in
	/usr/bin/pacman)
		sudo pacman -Syy
		ins "sudo pacman -S" "$1"
		echo "y" | sudo pacman -Su
		printf "\n-- QUERYING DATABASE FOR ORPHANS --\n"
		echo "ORPHANS:"
		sudo pacman -Qdt
		exit 0
	;;

	/usr/bin/apt)
		sudo apt update
		ins "sudo apt install" "$1"
		sudo apt upgrade -y
		printf "\n-- REMOVING UNUSED PACKAGES --\n"
		sudo apt autoremove -y
		exit 0
	;;

	/usr/bin/dnf)
		sudo dnf check-update
		ins "sudo dnf install" "$1"
		yes "y" | sudo dnf upgrade
		printf "\n-- REMOVING UNUSED PACKAGES --\n"
		echo "y" | sudo dnf autoremove
        exit 0
	;;

	/sbin/apk)
		apk update
		ins "apk add" "$1"
		apk upgrade
		exit 0
	;;

	/usr/sbin/pkg)
		ins "pkg install" "$1"
		echo "y" | pkg upgrade && echo "y" | pkg autoremove
		exit 0
	;;

	/usr/sbin/pkg_add)
		ins "pkg_add" "$1"
		pkg_add -u
		exit 0
	;;

	*)
		printf "\n-- PACKAGE MANAGER NOT FOUND --\n" && exit 1
	;;
esac

printf "autopac: invalid option -- '$1' \nTry --help for more information\n"
